### ISSUE TITLE
[Feature Request] Encryption - Password On Startup

### ISSUE THREAD

**Issue by trymeouteh** [LibreELEC/LibreELEC.tv#4910]
Many Linux distros such as Ubuntu can allow for encrypting the installation and then requiring a password to be entered on booting up to unlock the computer and boot into Linux. Please add this to LibreElec.

**Comment by chewitt** [comment]
Closing because a) this is a bug tracker not a feture request tracker, b) as per conversation in #4839 this is a niche feature that user numbers do not justify adding the dsitro bloat for. You are welcome to become the 25th user of the community image linked/discussed in that PR (or one of the many other distro's that run Kodi).
