### ISSUE TITLE
Media Importer 

### ISSUE THREAD

**Issue by rijsab** [LibreELEC/LibreELEC.tv#5444]
### Describe the bug

Media importer is not implemented in LibreElec. 

### To Reproduce
Media importer cannot be found or installed. 

### Informations
 - LibreElec (Longman) onofficial
 -Taspberry Pi 4

### Log file
No point to add in Log file. Addon is not available in current LibreElec. 

### Additional context
Longman implemented media importer on LibreElec and shared his version with me. Would expect this can be made available as well for official LibreElex

**Comment by chewitt** [comment]
This is a bug tracker and it's not possible for LE to have a bug in code it doesn't use, so this ticket will be closed. When the Media Import capabilities are merged into Kodi they will be available in the next major LE release. Until then the code is still under development and we prefer not to add WIP Kodi feature code; esp. when the code in question has been in gestation since 2015. Experience says anything that's been gestating for that long will probably take a while longer yet.
