### ISSUE TITLE
[BUG] Loop reboot on Orange Pi PC with LibreELEC 9.95.5

### ISSUE THREAD

**Issue by SNMetamorph** [LibreELEC/LibreELEC.tv#5482]
### Describe the bug
When trying to start device, boot process stuck with these messages in UART:
```
Starting kernel ...

[    0.001641] /cpus/cpu@0 missing clock-frequency property
[    0.001677] /cpus/cpu@1 missing clock-frequency property
[    0.001700] /cpus/cpu@2 missing clock-frequency property
[    0.001724] /cpus/cpu@3 missing clock-frequency property
[    0.110808] sun4i-usb-phy 1c19400.phy: Couldn't request ID GPIO
[    0.453904] sun4i-codec 1c22c00.codec: Failed to register our card
[    0.797530] debugfs: Directory '1c22c00.codec' with parent 'H3 Audio Codec' already present!
```

### Informations
 - LE Version: LibreELEC-H3.arm-9.95.5
 - Hardware Platform: Orange Pi PC

### How to fix
Remove "quiet" flag from extlinux.conf file

**Comment by jernejsk** [comment]
Why do you think kernel is stuck? Serial console disabled by default and kernel output on serial is intentionally minimized, since only few people use it. ssh is far better alternative, except if you want to debug boot problems. In that case, you should add `systemd.debug-shell=ttyS0` to extlinux.conf.

BTW, I tested OrangePi Plus2E (H3) two days ago and there is no boot issue. I don't have OrangePi PC, but it shouldn't be any different in this regard.
