### ISSUE TITLE
[BUG] On Pi 4 setting hdmi_pixel_encoding has no effect

### ISSUE THREAD

**Issue by maeries** [LibreELEC/LibreELEC.tv#5765]
### Describe the bug
No matter what I set `hdmi_pixel_encoding` to, it does not seem to have any effect

### To Reproduce
1. Put LibeELEC for Pi 4 on an SD card (I upgraded from 9,X to 10.0.0. Don't know if that's important)
2. Add `hdmi_pixel_encoding:0=2` to the config.txt
3. Start the Pi

### Expected Behavior
The Pi switches to full RGB which makes the output image darker

### Actual Behavior
Nocthing changes. The Pi stays at limited RGB

### Informations
 - LE Version: 10.0.0
 - Hardware Platform: Pi 4 2GB RAM

### Log file
http://ix.io/3BRt

### Additional context
I tried different variants like `hdmi_pixel_encoding=2` or 
```
hdmi_pixel_encoding:0=2
hdmi_pixel_encoding:1=2
```
but nothing worked

For the official docs go here: https://www.raspberrypi.com/documentation/computers/config_txt.html#hdmi_pixel_encoding

The Pi seems to read the config correctly:
```
LibreELEC:/flash # vcgencmd get_config int
arm_64bit=1
arm_freq=1500
audio_pwm_mode=514
config_hdmi_boost=5
core_freq=500
core_freq_min=200
disable_commandline_tags=2
disable_fw_kms_setup=1
disable_l2cache=1
disable_overscan=1
display_hdmi_rotate=-1
display_lcd_rotate=-1
dvfs=3
enable_gic=1
force_eeprom_read=1
force_pwm_open=1
framebuffer_ignore_alpha=1
framebuffer_swap=1
gpu_freq=500
gpu_freq_min=250
init_uart_clock=0x2dc6c00
lcd_framerate=60
mask_gpu_interrupt0=3072
mask_gpu_interrupt1=25635
max_framebuffers=-1
pause_burst_frames=1
program_serial_random=1
total_mem=2048
hdmi_force_cec_address:0=65535
hdmi_force_cec_address:1=65535
hdmi_ignore_cec_init:0=1
hdmi_pixel_encoding:0=2
hdmi_pixel_freq_limit:0=0x11e1a300
hdmi_pixel_freq_limit:1=0x11e1a300
```

**Comment by chewitt** [comment]
@HiassofT am I correct in thinking this config item is no longer supported under the new driver stack used in LE10?

**Comment by HiassofT** [comment]
That's correct, the hdmi_... settings are only honored by the legacy graphics stack and currently there's no equivalent of that option in the kms driver

**Comment by maeries** [comment]
That's too bad as setting the GPU to full RGB is actually recommended to avoid banding. This article is very helpful on this topic https://kodi.wiki/view/Video_levels_and_color_space#Which_Combination_to_Use

**Comment by HiassofT** [comment]
I beg to differ. Videos are stored with limited range and CTA/HDMI modes (eg 1920x1080) use limited range as well - so if you play a SD/HD/4k video it'll be output 1:1 without adjusting luminance in the output path.

Only DMT (aka "PC" video modes, like 640x480, 1920x1200...) use full range. In that case video luminance needs to be scaled up from limited to full.

The vc4 driver correctly outputs limited for CTA and full range for DMT modes. Forcing full range on CTA modes is only needed to workaround bugs in a bunch of broken, ancient monitors which don' t support CTA modes properly and display them as if they'd contain full range - with dark gray instead of black and white not as bright as it should be.

**Comment by maeries** [comment]
This is getting off topic, but I'm really interested in this discussion. Tbh, I don't really understand your way of reasoning as I don't know what CTA and DMT are exactly, but you are implying that the article I linked is wrong. Though, it corresponds with my observations. Currently I'm running the Full, Limited, Limited option from the article as that's the only correct option when the GPU is set to limited and like in the article the blacker-that-black gets cut off. Meanwhile, with Kodi on my PC, I use Limited, Full, Limited and I can see the blacker-that-blacks then I change the brightness setting on my TV

**Comment by HiassofT** [comment]
Actually it's quite simple: everything in the video pipeline is limited - video is decoded into YCbCr plane and output as limited - assuming you use a standard HDMI mode like 1920x1080, and TVs expect that to be the case - so no conversion takes place.

Note that the video is not rendered to a full-range RGB plane, like it's often done on PCs which would then need to be converted down into limited for normal HDMI modes.

So the question is which problem are you actually trying to solve? TVs are optimized for limited video input, so if you force a limited->full conversion on video output on the RPi you are not feeding the TV with the signal it has been optimized for...

**Comment by maeries** [comment]
> Note that the video is not rendered to a full-range RGB plane, like it's often done on PCs which would then need to be converted down into limited for normal HDMI modes.

Does that mean that the Pi renders video differently than a PC?

> So the question is which problem are you actually trying to solve?

Currently the colors blacker-than-black are clipping. Meaning that on testvideos I cannot see a difference between brightness 0 and brightness 16. That's not a problem in itself, but i suspect it beeing an indicator for another problem that causes banding issues, but I havn't checked that yet.

> TVs are optimized for limited video input, so if you force a limited->full conversion on video output on the RPi you are not feeding the TV with the signal it has been optimized for...

I get that, but according to the article setting the stack to limited, full, limited is the option that does not do any conversion

**Comment by HiassofT** [comment]
Yes, rendering when using the DRM PRIME renderer is different. Kodi GUI is rendered to a RGB full range 8bit graphics plane and video to a separate plane which is usually YCbCr 8 or 10 bit. These planes are then mixed together (with alpha-blending etc) internally in the graphics chip. That happens with high enough precision so that there shouldn't be information lost.

I wouldn't worry about values outside of the valid quantization range, they should be clipped to black/white by the display anyways, it's more important you calibrate your display so that the values at the end of the valid range can be distinguished (black 16 vs very dark grey at 17/18 etc).

**Comment by heitbaum** [comment]
Closing as “answered” please reopen if required for further discussion
