### ISSUE TITLE
[BUG] LE 10 RPI4 resulting in repeated hdmi signal loss.

### ISSUE THREAD

**Issue by sp00ktober** [LibreELEC/LibreELEC.tv#5788]
### Describe the bug
The TV looses the HDMI signal for a few seconds. After that the video and audio is back, audio seems to "catchup" to where it should be without the short signal loss.
This seems to happen randomly and without any specific pattern, sometimes the singal does not come back and i need to hard reset the RPI.

I asked about it on the forum too, you can find it [here](https://forum.libreelec.tv/thread/24598-le10-rpi4-hdmi-signal-losses-up-to-black-screen/)

### To Reproduce
Start the RPI4 with LE 10 installed and just wait until it happens. I did change the HDMI cables between media receiver and RPI with no difference.

### Informations
- LE 10
- RPI4 4 GB
- 3A power supply for the RPI
- System installed on an external SSD connected using a self powered SATA to USB3 adapter.
- One additional HDD with its own power supply connected over USB
- Ethernet for Internet
- HDMI cable that came with the RPI to connect to media receiver, media receiver connected over HDMI to the TV.

### Log file
[here](http://ix.io/3AhW) is the logfile i referenced in the [forum post](https://forum.libreelec.tv/thread/24598-le10-rpi4-hdmi-signal-losses-up-to-black-screen/).

### Additional context
The problem was fixed by going back to LE 9.2.8. The only thing that i can notice there is the lighning bold symbol in the upper right corner which is visible some times, but beside that no signal loss, no stuttering. Everything works very fine there.

**Comment by Shamp0o** [comment]
I've been having pretty much the same issue with LE10 on a Rpi4 with the official power supply and nothing connected to the USB ports. Upgrading to LE10.0.1 didn't help. 

What's interesting is that this never happens when playing 4k HDR videos. It only happens with 1080p videos (not all of them i think) or VOD/live streams and in the Kodi UI. 

It's been a while since I used LE9 but I'm pretty sure this issue first appeared with LE10.

I'm willing to provide logs and do some more investigations if needed.
