### ISSUE TITLE
Kodi runs as root

### ISSUE THREAD

**Issue by fugkco** [LibreELEC/LibreELEC.tv#6473]
### Describe the bug
On a default installation, kodi seems to be running as root. This is insecure. It would be great if we this can be changed to run kodi as a non-root user. Creating a new user should be trivial though I'm not sure how it would work when it comes to running having systemd run Kodi.

Running kodi as root means that if something compromises Kodi, the whole system is compromised. 

### To Reproduce
```
LibreELEC:~ # ps aux | grep [k]odi
  772 root      0:00 {kodi.sh} /bin/sh /usr/lib/kodi/kodi.sh --standalone -fs
  776 root      1h52 /usr/lib/kodi/kodi.bin --standalone -fs
```

### Informations
```
LibreELEC:~ # cat /etc/os-release 
NAME="LibreELEC"
VERSION="10.0.2"
ID="libreelec"
VERSION_ID="10.0"
PRETTY_NAME="LibreELEC (official): 10.0.2"
HOME_URL="https://libreelec.tv"
BUG_REPORT_URL="https://github.com/LibreELEC/LibreELEC.tv"
BUILD_ID="8fd15cdad59fb70083aa25b5c9680d8826b94696"
LIBREELEC_ARCH="RPi4.arm"
LIBREELEC_BUILD="official"
LIBREELEC_PROJECT="RPi"
LIBREELEC_DEVICE="RPi4"
```

**Comment by chewitt** [comment]
It's not impossible to make Kodi run as a non-root user and we have previously thought about how it could be done within the constraints of our non-standard OS packaging, but it's not an item on our current roadmap. As such I'm going to close this issue here, as while the current design may not be perfect, the current design is also intentional thus there is no bug (and this is a bug tracker). NB: Submissions of working (and simple considering our userbase) multi-user implementations for our distro are always welcome.
