### ISSUE TITLE
[BUG] Cannot change screen brightness on a laptop

### ISSUE THREAD

**Issue by erayrafet** [LibreELEC/LibreELEC.tv#6869]
### Describe the bug
The brightness keys on my laptop do not change the display brightness. Only way is to ssh and echo the value in /sys/class/backlight.

### Informations
 - LE Version: 11 nightly from September the 2nd
 - Hardware Platform: HP Pavilion 13-AN007NU (Intel I5-8265U, UHD620)

### Additional context

I can try the stable version if necessary.

**Comment by chewitt** [comment]
I'm closing the ticket because this is a bug tracker and we can't have a bug in a feature we don't have; which historically is because we target HTPC devices that don't need display controls [for the display they don't have]. We don't mind people using old laptops, but they have never been target hardware. If you're an optimist, feature requests belong in the forum :)
