### ISSUE TITLE
Tvheadend 10.0.0.126 does not start

### ISSUE THREAD

**Issue by movedoa** [LibreELEC/LibreELEC.tv#7400]
My libreelec installation just updated the tvheadend server addon to 10.0.0.126 (after i updated to libreelec 10.0.4 from 10.0.2) but it doesn't start anymore. 
Looks like there is a file missing.

This is the error from the 11_Addons.log:

```
################################################################################
# ... output of cat /storage/.kodi/userdata/addon_data/service.tvheadend42/service.log
# LibreELEC release: Generic.x86_64-10.0.4
# 
################################################################################
/storage/.kodi/addons/service.tvheadend42/bin/tvheadend: error while loading shared libraries: libx265.so.199: cannot open shared object file: No such file or directory
```

I rolled back to 10.0.0.125 for now. If you need more information just let me know.

**Comment by heitbaum** [comment]
Logic for the shared library change x265 has not been added to tvheadend42.

https://github.com/LibreELEC/LibreELEC.tv/blob/2a36dd09c3ce264b1ae79c25755c44b97320dc34/packages/addons/service/tvheadend43/package.mk#L126-L128

- this was fixed in #5623 - will backport tvheadend43 changes to tvheadend42 (both LE10/11)
