### ISSUE TITLE
[BUG] No sound via HDA Nvidia , HDMI

### ISSUE THREAD

**Issue by alexhass** [LibreELEC/LibreELEC.tv#7986]
### Describe the bug
Generic Legacy build have no Audio via HDMI. This is a serious problem. This worked perfectly until 9.x. There are tons of reports about the same bug in forum.

### To Reproduce
1. install legacy generic on zotac ion
2. connect to tv and run tv (e.g. tvheadend)
3. no sound

### Informations
 - LE Version: tested up to nightly 15.07.2023
 - Hardware Platform: Zotac ION

**Comment by alexhass** [comment]
The bug still exists in 11.0.3. 

The forum has tons of comments about the same defect.

**Comment by heitbaum** [comment]
Unfortunately without much to go on in this issue unable to address this.

Nvidia is not a recommended video card as you may be aware. https://wiki.libreelec.tv/hardware/intel-x86-64-generic

Raising a bug here won’t get your issue fixed as the development team do not develop or have nvidia to test with so the forum is the right place for support - hopefully another user has experience with this issue -  if a solution can be found there - then would be able to address this in development. 

Your issue seems to be isolated to an audio issue - so suggest your forum post identifies this as the issue. 

There have been recent updates to the nvidia packages in LE - and will continue - but are only for the modern cards.

**Comment by alexhass** [comment]
There are many others in forums reporting the same issue. Looks like the new driver is not working properly. In LE9.3 ist works. Have no read about any workaround or other installed driver that works yet.
