### ISSUE TITLE
LibreELEC RPi4 11.0.3 ntp not updating clock and can't paste logs

### ISSUE THREAD

**Issue by Bigjohn4** [LibreELEC/LibreELEC.tv#8419]
### Describe the bug
I had been running LibreELEC / Kodi on RPi3 for years with no issues. Decided to upgrade RPi to RPi4. Installed LibreELEC RPi4 Arm 11.0.3. Everything works except the clock is not being set. I added NTP servers, but that did not help. I can SSH and set date/time, but it drifts and is lost across reboot. pastekodi did not seem to work, see below. Is there another to send logs now?

LibreELEC (official): 11.0.3 (RPi4.arm)
LibreELEC:~ # pastekodi
LibreELEC:~ #
 Also, there is no Paste Logs option under System in the GUI. Do I need an add-on for pasting logs?

### How to reproduce
happens all the time since upgrade

### Information
 - LibreELEC Version: [e.g. 9.2.1]  11.0.3
 - Hardware Platform: [e.g. RPi3] RPi4

**Comment by chewitt** [comment]
I'm closing the ticket here as the issue with ix.io paste (currently down) is known and resolved with a switch to our own self-hosted paste site in a pending 11.0.4 release, see https://github.com/LibreELEC/LibreELEC.tv/pull/8412. Everything else is normal behaviour for a device with no RTC chip; except for why NTP is not working in your network. However this is a bug tracker and that's something odd about your environment, so that's something to open a thread on in our support forum: https://forum.libreelec.tv. Thanks.
